fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-added-large-files
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: debug-statements
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.2
  hooks:
  - id: reorder-python-imports
    args: [--py37-plus]
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.3
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.20.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.7.0
  hooks:
  - id: autopep8
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: [--max-line-length=127]
