- id: check-include-guards
  name: check include guards
  entry: check-include-guards
  description: Cheks for unique relative named C header include guards
  types_or: [c, c++]
  language: python

- id: check-hex-case
  name: check hex case
  entry: check-hex-case
  description: Checks and fixes hex number declarion case, as in upper/lower
  types_or: [c, c++]
  language: python
